# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: From Omeka Classic to Omeka Semantic
email: daniel.github@berthereau.net
description: > # this means to ignore newlines until "baseurl:"
  These pages simplify migration from Omeka 2 (Omeka Classic) to Omeka S and
  bring together all available tools on the web about Omeka Classic et Omeka S.
  For missing or new plugins or any other need on Omeka and digital collections,
  don’t hesitate to contact us!
baseurl: "/UpgradeToOmekaS"
# url: "https://daniel-km.github.com"
# permalink: /UpgradeToOmekaS/:file:output_ext
twitter_username:
github_username:  Daniel-KM

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  # - jekyll-polyglot

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# I18n
# Polyglot
# @see https://leo3418.github.io/collections/multilingual-jekyll-site
languages: ["en", "fr"]
# To keep redirection from old pages, default language should be "en" for now.
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public", "assets"]
parallel_localization: true

sass:
  sourcemap: never
