title: "D’Omeka Classic à Omeka Semantic"
description: >
  Ces pages simplifient la migration d’Omeka 2 (Omeka Classic) à Omeka S et
  rassemble les outils disponibles sur le web concernant Omeka Classic et Omeka S.
  Pour les extensions absentes ou les nouvelles fonctionnalités ou tout autre
  besoin sur Omeka et les bibliothèques numériques, n’hésitez pas à nous
  contacter.
lang_name: "Français"
