title: "From Omeka Classic to Omeka Semantic"
description: >
  These pages simplify migration from Omeka 2 (Omeka Classic) to Omeka S and
  bring together all available tools on the web about Omeka Classic et Omeka S.
  For missing or new plugins or any other need on Omeka and digital libraries,
  don’t hesitate to contact us!
lang_name: "English"
